# https://github.com/AshenCat/assignment

language: node_js
node_js:
  - 10.9.0

cache: npm

env:
  NOW_TOKEN: j4ei0j8Rxd5NT06tXCuuQyRL

install:
  - "npm config set spin false"
  - npm install -g now

script:
  - npm run build
  - npm run test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true